export const enum GET_PRODUCT_DETAILS_ACTION {
  PENDING = 'GET_PRODUCT_DETAILS_BY_ID_PENDING',
  SUCCESS = 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
  FAILURE = 'GET_PRODUCT_DETAILS_BY_ID_FAILURE',
}

export type ACTION = GET_PRODUCT_DETAILS_ACTION;
